#CbqRAya0 Register drivers and operators
atlp-rwanda/cabal-phantom-frontend pull request #7
Opened 2020-12-10 22:16 UTC by ncutixavier

### **What about this PR?**
This PR is about to register driver and operators.

### **Description of Task to be completed**
- Admin should register users
- Skeleton should appeared when page is loading
- Page should be resposive

### **How should be tested?**
- To be filled soon
 
### **Relevant pivots tracker**
[#CbqRAya0](https://trello.com/c/CbqRAya0/36-register-drivers-operators)

2020-12-22 12:53 UTC, karigirwa commented
It is impossible to register with a gender of Male  you can add some validation, but also after registering someone an approval message may be says "successfully registered" is needed.

2020-12-22 13:31 UTC, Niyiragira commented
> It is impossible to register with a gender of Male you can add some validation, but also after registering someone an approval message may be says "successfully registered" is needed.

Your review has been worked on

2020-12-31 09:46 UTC, Niyiragira submitted a review, later dismissed

2020-12-31 10:51 UTC, ceelogre requested changes
Date is not validated, messages are not translated.
![Capture d’écran 2020-12-31 à 12 29 52](https://user-images.githubusercontent.com/5022823/103407195-5e8d5480-4b66-11eb-96fe-58d6d8ee3c27.png)


I'm unable to sign in with the new account credentials (email & password)

![Capture d’écran 2020-12-31 à 12 33 48](https://user-images.githubusercontent.com/5022823/103407209-75cc4200-4b66-11eb-909e-0331067d335f.png)


Also, your diffs are too large so it's hard to review the code. It seems you cut and re-pasted most of the content of the files especially in components, for example:

![Capture d’écran 2020-12-31 à 12 50 47](https://user-images.githubusercontent.com/5022823/103407286-d2c7f800-4b66-11eb-9a22-f1b55d985a63.png)

2021-01-07 07:49 UTC, ceelogre approved these changes

2021-01-07 08:00 UTC, Niyiragira approved these changes

2021-01-07 08:03 UTC, karigirwa approved these changes

2021-01-07 09:21 UTC, merged